### ISSUE TITLE
How to deal with admin and site abilities?

### ISSUE THREAD

**Issue by mocerinoj** [jrabolli/operator#14]
1) We could go full blown user accounts and roles to allow for admin editing and site-level alerts. 

2) Use a simple password to access those tools

3) Do nothing for now

**Comment by jrabolli** [comment]
I think for MVP, option 2 - simple password makes sense.  They will really replace the wiki with our MVP (soon) so a simple password makes some sense to keep things under control but I don't see a need to full blown until we have stories that require that level.
