### ISSUE TITLE
Admin facility editing

### ISSUE THREAD

**Issue by mocerinoj** [jrabolli/operator#15]
As an admin, I need to edit facility info to keep operator up to date.

Which fields need to be editable?

**Comment by jrabolli** [comment]
I think for MVP, we add services to facility admin/edit and thats it.  I am sure in reality if I ask they will say they want to be able to update everything as well as add new facilities and delete.  But I do not think that is necessary right now.  Everything seems static enough other than services that it should not be needed for several iterations.

**Comment by mocerinoj** [comment]
Cool, yea I figured services.
