### ISSUE TITLE
site wide search needs to consider facility services

### ISSUE THREAD

**Issue by jrabolli** [jrabolli/operator#57]
as a PCA, I need the main site search to include searching for the facility service as well, so I can easily identify a direction total the call.  Example might be I search for 'dental' - any facility that has dental as a service should maybe be returned.  right now I think it does a similar thing for provider 'specialty'

**Comment by mocerinoj** [comment]
I can add services to search consideration.. what about displaying in the results? Currently, we are showing city, state of the facility.. can this be replaced with services?
