### ISSUE TITLE
phone extensions

### ISSUE THREAD

**Issue by jrabolli** [jrabolli/operator#58]
As a PCA, I need the phone extension listed in the provider partial, because I often need to transfer patient calls to the nurse at that location.

**Comment by jrabolli** [comment]
the reality is they are only really allowed to transfer to non-doctors (nurse, care manager etc) but if we are adding the extension we might as well list them for any 'type' of provider for now rather than create some crazy logic to distinguish.

**Comment by mocerinoj** [comment]
This needs more detail.. you are saying there is a nurse extension per provider that we need to add? And we need to expose this in the provider partial on the facility page?

**Comment by jrabolli** [comment]
well I am saying that we have a mix of different types or 'providers' right now in our table and thus our partial (doctors, nurses, care coordinators etc) and for the Nurses at least the PCA's need the phone extension in the partial.  I would imagine there is no harm in showing an extension for any type of provider even though they currently only NEED it for nurses.  I believe they are discourage from calling doctors directly for instance.
