### ISSUE TITLE
provider exclusions - discrete data, not free text

### ISSUE THREAD

**Issue by jrabolli** [jrabolli/operator#74]

**Comment by mocerinoj** [comment]
> and he wants to get rid of provider exclusions and have provider services instead and have that be discrete data which he is getting me asap

Rename the column, update UI work like facility services?

**Comment by jrabolli** [comment]
so yes, instead of exclusions, its now going to be services (inclusions) so it will be just like services for facility.  but both now need to be discrete data.  I am waiting for the provider services.

**Comment by jrabolli** [comment]
just like #76

**Comment by jrabolli** [comment]
Pediatric only
New Patient
Pap
Depo
Nexplanon Insertion
Nexplanon removal
IUD Insertion
IUD removal
Birth Control Pills  (Contraceptives)
MAT
MAT only
Speciality
Pediatric only Referral needed if not HRHcare patient.
Adult patients
DOT
NO Fault
Workers Comp
Colposcopies
LEEP
Centering
In house referal
Children 6 months and up
Children 0 & 17 ages
Children 1 & up ages
Children 2 & up ages
Children 3 & up ages
Children 5 & up ages
Children 7 & up ages
Children 10 & up ages
Children 12 & up ages
Patients  18 & up ages
Patients 16 & up ages
Patient s 17 & up ages
Children 0 to 19 ages
All age range
High Rick OB
Family Planning
GYN
GYN under 40
Womans Health
Per Diem
Prenatal (Obstetrics)
Only Hrhcare patients
Genesis
Adults
Outside referrals accepted
STD testing
Prep
Endometrial biopsy
Anoscopy
Ultrasonography
Diagnosis & treatment of emotional illness
Diagnosis & treatment of alcoholism
Diagnosis & treatment of drug abuse
Diagnosis & treatment of abused children, spouses, parents
HIV Counseling
Patient Education
Routine diagnosis and treatment of lower extremity (below knee)
Minor surgical procedures of the foot
Nail Care
Casting
Orthotics
Patient Education
