### ISSUE TITLE
call center workflow (initial)

### ISSUE THREAD

**Issue by jrabolli** [jrabolli/operator#8]
as a call center rep, I take a call and need to with the least clicks possible find the closest facility and identify the most appropriate provider from the facility for the callers needs (simple geo lookup? zip?)

**Comment by jrabolli** [comment]
do you agree with using Geocoder gem here?  If so, I can start working on this under a separate branch.  If you have a different better way, I can hold off

**Comment by mocerinoj** [comment]
Geocoder will just geocode stuff. Geokit is more of adult service. Perhaps
we should discuss? Also you will need to pay for a google account. Most
likely you will stay in the free range but you need a credit card now to
set it up I believe.

**Comment by jrabolli** [comment]
closing this as it will be part of the continual UI design and GeoCoder ideas have been rendered not needed.  this should be taken care of with the eCW integration
