### ISSUE TITLE
email (password change) not working properly

### ISSUE THREAD

**Issue by jrabolli** [jrabolli/operator#85]
configuration

**Comment by jrabolli** [comment]
even after adding `  config.action_mailer.default_url_options = { host: "hrhc-operator.herokuapp.com" }
` it fails for a different reason.  now we get 

> [2019-07-08T15:41:23.049764 #4] FATAL -- : [7b4436b9-b58f-4fce-b370-3b64178536d4] Net::SMTPAuthenticationError (535 Authentication failed: Bad username / password

do these settings look correct to you? 
`config.action_mailer.perform_caching = false

  config.action_mailer.default_url_options = { host: "hrhc-operator.herokuapp.com" }
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.perform_deliveries = true
  config.action_mailer.smtp_settings = {
    user_name: ENV["SENDGRID_USERNAME"],
    password: ENV["SENDGRID_PASSWORD"],
    domain: "yourdomain.com",
    address: "smtp.sendgrid.net",
    port: 587,
    authentication: :plain,
    enable_starttls_auto: true
  }`

**Comment by mocerinoj** [comment]
Looks like the ENV vars had an extra carriage return in the string.. I updated it.. we can retest in a bit

**Comment by jrabolli** [comment]
I believe this is resolved now.
