### ISSUE TITLE
provider hours not showing

### ISSUE THREAD

**Issue by jrabolli** [jrabolli/operator#94]
provider hours (schedule) are being entered through the admin screen and do show on the admin screen.  However when you click on that provider in the non admin screen (provider partial) it does not show the hours, it shows 'hours unavailable'.  I confirmed the data is there.

**Comment by mocerinoj** [comment]
Can you provide an example of this? with links?

**Comment by jrabolli** [comment]
https://hrhc-operator.herokuapp.com/admin/providers/10/edit

<img width="1792" alt="Screen Shot 2019-07-12 at 11 22 08 AM" src="https://user-images.githubusercontent.com/89401/61139464-5b486980-a497-11e9-8232-29b39a0822a6.png">

https://hrhc-operator.herokuapp.com/providers/10

<img width="1792" alt="Screen Shot 2019-07-12 at 11 23 25 AM" src="https://user-images.githubusercontent.com/89401/61139539-816e0980-a497-11e9-9e4f-f2d3d8346928.png">
